### ISSUE TITLE
Network doesn't sort numerically

### ISSUE THREAD

**Issue by evelynmitchell** [yeo/ec2.shop#10]
When sorting high to low, 10 Gbps shows up before 100 Gbps, which is wrong.

**Comment by v9n** [comment]
thanks @evelynmitchell going to fix it

**Comment by v9n** [comment]
@evelynmitchell I fixed it. We have custom sorting logic now now. https://github.com/yeo/ec2.shop/blob/master/static/js/app.js#L4-L43

**Comment by evelynmitchell** [comment]
Looks a lot better. 75 GB is out of order.

**Comment by v9n** [comment]
@evelynmitchell Oh sorry. can you believe it? I forgot to deploy haha. It should work properly now I promise.

<img width="269" alt="Screen Shot 2020-08-04 at 1 43 36 PM" src="https://user-images.githubusercontent.com/49754/89343036-85e40200-d658-11ea-80a4-d27c6a990298.png">
<img width="239" alt="Screen Shot 2020-08-04 at 1 43 29 PM" src="https://user-images.githubusercontent.com/49754/89343041-88465c00-d658-11ea-99aa-5b966b1930b0.png">
<img width="206" alt="Screen Shot 2020-08-04 at 1 43 23 PM" src="https://user-images.githubusercontent.com/49754/89343044-88def280-d658-11ea-8ca9-6110afc17506.png">
