### ISSUE TITLE
Sorting of numerical columns is done lexicographically

### ISSUE THREAD

**Issue by MarkSRobinson** [yeo/ec2.shop#2]
The vCPU and memory column are sorted lexicographically instead of numerically.  So the ordering is 0, 1, 116, 120,...,2.

**Comment by brandonros** [comment]
Price too.

**Comment by v9n** [comment]
Hey,

Thank for the bug report. I fixed all of sorting issue in https://github.com/yeo/ec2.shop/commit/71659a33d0daf5bb6bb9fb88e7bf1f6708c8070e 

and deploy it :-). Give it another try.
