### ISSUE TITLE
Can't do secondary sorting

### ISSUE THREAD

**Issue by MarkSRobinson** [yeo/ec2.shop#5]
I'd like to be able to sort of multiple columns.  For example, I'd like to sort on memory first, then on price.

Usually this is implemented by using a stable sorting algo and then sorting the data multiple times.  From a UI perspective I'd click price, then click memory.

Right now, that doesn't work.  If I sort by price then memory, It's not sorted by price anymore.

**Comment by v9n** [comment]
thanks for report the issue. That makes sense. I'll gix it.

**Comment by v9n** [comment]
@MarkSRobinson This is implemented now. You can hold the Shift key to sort by multiple fields.
