### ISSUE TITLE
Setting JSON return type nullfies any filters

### ISSUE THREAD

**Issue by hahuang65** [yeo/ec2.shop#6]
`curl --silent "https://ec2.shop?filter=m4" --header 'accept: json'`

will seemingly return all instance types whereas

`curl --silent "https://ec2.shop?filter=m4"`

will return just m4 instances

**Comment by v9n** [comment]
@hahuang65 Sorry for the issue. It should be fixed now.

**Comment by hahuang65** [comment]
Awesome! Thanks for the quick fix!

**Comment by v9n** [comment]
``
